name: Deploy to frontend
on:
  push:
  branches: [ master ]
jobs:
    build:
    runs-on: ubuntu:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/build-push-action@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    -name: Docker build and push
     uses: docker/build-push-action@v7
     with:
       context: .
       file: ./Docker/Dockerfile.frontend
       push: true
       tags: adarsh1606/todo-app-frontend.${{github.sha}}

       
